// TexCom's languages: BCP-47 code, name in the language itself, English name, text direction, and the words the
// Yes / No toolbar buttons say. Phrase sets for these are in languages/phrases/<code>.json on texcom.pages.dev
// (English is built in: TexCom.json). The other sets were machine translated and not yet checked by a speaker.
// gemini: the code Gemini's translation run used (translation-tools/raw), where it differs.
window.TEXCOM_LANGUAGES = [
    { code: 'en', native: 'English', english: 'English', yes: 'Yes', no: 'No' },
    { code: 'af', native: 'Afrikaans', english: 'Afrikaans', yes: 'Ja', no: 'Nee', gemini: 'afr' },
    { code: 'ar', native: 'العربية', english: 'Arabic', dir: 'rtl', yes: 'نعم', no: 'لا' },
    { code: 'hy', native: 'Հայերեն', english: 'Armenian', yes: 'Այո', no: 'Ոչ' },
    { code: 'as', native: 'অসমীয়া', english: 'Assamese', yes: 'হয়', no: 'নহয়' },
    { code: 'be', native: 'Беларуская', english: 'Belarusian', yes: 'Так', no: 'Не', gemini: 'bel' },
    { code: 'bn', native: 'বাংলা', english: 'Bengali', yes: 'হ্যাঁ', no: 'না', gemini: 'be' },
    { code: 'bho', native: 'भोजपुरी', english: 'Bhojpuri', yes: 'हँ', no: 'ना', gemini: 'bh' },
    { code: 'bg', native: 'Български', english: 'Bulgarian', yes: 'Да', no: 'Не' },
    { code: 'my', native: 'မြန်မာစာ', english: 'Burmese', yes: 'ဟုတ်ကဲ့', no: 'မဟုတ်ဘူး' },
    { code: 'ca', native: 'Català', english: 'Catalan', yes: 'Sí', no: 'No' },
    { code: 'ny', native: 'Chichewa', english: 'Chichewa', yes: 'Inde', no: 'Ayi' },
    { code: 'zh-Hans', native: '中文（简体）', english: 'Chinese (Simplified)', yes: '是的', no: '不是', gemini: 'zhc' },
    { code: 'zh-Hant', native: '中文（繁體）', english: 'Chinese (Traditional)', yes: '是的', no: '不是', gemini: 'zh' },
    { code: 'hr', native: 'Hrvatski', english: 'Croatian', yes: 'Da', no: 'Ne' },
    { code: 'cs', native: 'Čeština', english: 'Czech', yes: 'Ano', no: 'Ne' },
    { code: 'da', native: 'Dansk', english: 'Danish', yes: 'Ja', no: 'Nej' },
    { code: 'nl', native: 'Nederlands', english: 'Dutch', yes: 'Ja', no: 'Nee' },
    { code: 'eo', native: 'Esperanto', english: 'Esperanto', yes: 'Jes', no: 'Ne' },
    { code: 'et', native: 'Eesti', english: 'Estonian', yes: 'Jah', no: 'Ei' },
    { code: 'fil', native: 'Filipino', english: 'Filipino', yes: 'Oo', no: 'Hindi' },
    { code: 'fi', native: 'Suomi', english: 'Finnish', yes: 'Kyllä', no: 'Ei' },
    { code: 'fr', native: 'Français', english: 'French', yes: 'Oui', no: 'Non' },
    { code: 'ka', native: 'ქართული', english: 'Georgian', yes: 'დიახ', no: 'არა' },
    { code: 'de', native: 'Deutsch', english: 'German', yes: 'Ja', no: 'Nein' },
    { code: 'el', native: 'Ελληνικά', english: 'Greek', yes: 'Ναι', no: 'Όχι' },
    { code: 'gu', native: 'ગુજરાતી', english: 'Gujarati', yes: 'હા', no: 'ના' },
    { code: 'he', native: 'עברית', english: 'Hebrew', dir: 'rtl', yes: 'כן', no: 'לא' },
    { code: 'hi', native: 'हिन्दी', english: 'Hindi', yes: 'हाँ', no: 'नहीं' },
    { code: 'hu', native: 'Magyar', english: 'Hungarian', yes: 'Igen', no: 'Nem' },
    { code: 'is', native: 'Íslenska', english: 'Icelandic', yes: 'Já', no: 'Nei' },
    { code: 'ga', native: 'Gaeilge', english: 'Irish', yes: 'Sea', no: 'Ní hea' },
    { code: 'it', native: 'Italiano', english: 'Italian', yes: 'Sì', no: 'No' },
    { code: 'ja', native: '日本語', english: 'Japanese', yes: 'はい', no: 'いいえ' },
    { code: 'kn', native: 'ಕನ್ನಡ', english: 'Kannada', yes: 'ಹೌದು', no: 'ಇಲ್ಲ' },
    { code: 'kk', native: 'Қазақша', english: 'Kazakh', yes: 'Иә', no: 'Жоқ' },
    { code: 'km', native: 'ខ្មែរ', english: 'Khmer', yes: 'បាទ', no: 'ទេ' },
    { code: 'rw', native: 'Ikinyarwanda', english: 'Kinyarwanda', yes: 'Yego', no: 'Oya' },
    { code: 'kok', native: 'कोंकणी', english: 'Konkani', yes: 'हय', no: 'ना' },
    { code: 'ko', native: '한국어', english: 'Korean', yes: '네', no: '아니요' },
    { code: 'ckb', native: 'کوردیی ناوەندی', english: 'Kurdish (Sorani)', dir: 'rtl', yes: 'بەڵێ', no: 'نەخێر' },
    { code: 'lo', native: 'ລາວ', english: 'Lao', yes: 'ແມ່ນ', no: 'ບໍ່' },
    { code: 'lv', native: 'Latviešu', english: 'Latvian', yes: 'Jā', no: 'Nē' },
    { code: 'lt', native: 'Lietuvių', english: 'Lithuanian', yes: 'Taip', no: 'Ne' },
    { code: 'lg', native: 'Luganda', english: 'Luganda', yes: 'Yee', no: 'Nedda' },
    { code: 'ms', native: 'Bahasa Melayu', english: 'Malay', yes: 'Ya', no: 'Tidak' },
    { code: 'ml', native: 'മലയാളം', english: 'Malayalam', yes: 'അതെ', no: 'ഇല്ല' },
    { code: 'mi', native: 'Te Reo Māori', english: 'Māori', yes: 'Āe', no: 'Kāo', gemini: 'mao' },
    { code: 'mr', native: 'मराठी', english: 'Marathi', yes: 'हो', no: 'नाही' },
    { code: 'mn', native: 'Монгол', english: 'Mongolian', yes: 'Тийм', no: 'Үгүй' },
    { code: 'ne', native: 'नेपाली', english: 'Nepali', yes: 'हो', no: 'होइन' },
    { code: 'no', native: 'Norsk', english: 'Norwegian', yes: 'Ja', no: 'Nei' },
    { code: 'or', native: 'ଓଡ଼ିଆ', english: 'Odia', yes: 'ହଁ', no: 'ନା' },
    { code: 'fa', native: 'فارسی', english: 'Persian', dir: 'rtl', yes: 'بله', no: 'نه' },
    { code: 'pl', native: 'Polski', english: 'Polish', yes: 'Tak', no: 'Nie' },
    { code: 'pt', native: 'Português', english: 'Portuguese', yes: 'Sim', no: 'Não' },
    { code: 'pa', native: 'ਪੰਜਾਬੀ', english: 'Punjabi', yes: 'ਹਾਂ', no: 'ਨਹੀਂ', gemini: 'pu' },
    { code: 'ro', native: 'Română', english: 'Romanian', yes: 'Da', no: 'Nu' },
    { code: 'ru', native: 'Русский', english: 'Russian', yes: 'Да', no: 'Нет' },
    { code: 'gd', native: 'Gàidhlig', english: 'Scottish Gaelic', yes: 'Tha', no: 'Chan eil' },
    { code: 'sr', native: 'Српски', english: 'Serbian', yes: 'Да', no: 'Не' },
    { code: 'st', native: 'Sesotho', english: 'Sesotho', yes: 'E', no: 'Tjhe', gemini: 'sot' },
    { code: 'si', native: 'සිංහල', english: 'Sinhala', yes: 'ඔව්', no: 'නැහැ', gemini: 'sin' },
    { code: 'sk', native: 'Slovenčina', english: 'Slovak', yes: 'Áno', no: 'Nie' },
    { code: 'sl', native: 'Slovenščina', english: 'Slovenian', yes: 'Da', no: 'Ne' },
    { code: 'es', native: 'Español', english: 'Spanish', yes: 'Sí', no: 'No' },
    { code: 'sw', native: 'Kiswahili', english: 'Swahili', yes: 'Ndiyo', no: 'Hapana' },
    { code: 'sv', native: 'Svenska', english: 'Swedish', yes: 'Ja', no: 'Nej' },
    { code: 'ta', native: 'தமிழ்', english: 'Tamil', yes: 'ஆம்', no: 'இல்லை' },
    { code: 'tt', native: 'Татарча', english: 'Tatar', yes: 'Әйе', no: 'Юк' },
    { code: 'te', native: 'తెలుగు', english: 'Telugu', yes: 'అవును', no: 'కాదు' },
    { code: 'th', native: 'ไทย', english: 'Thai', yes: 'ใช่', no: 'ไม่ใช่' },
    { code: 'tr', native: 'Türkçe', english: 'Turkish', yes: 'Evet', no: 'Hayır' },
    { code: 'uk', native: 'Українська', english: 'Ukrainian', yes: 'Так', no: 'Ні' },
    { code: 'ur', native: 'اردو', english: 'Urdu', dir: 'rtl', yes: 'ہاں', no: 'نہیں' },
    { code: 'uz', native: 'Oʻzbekcha', english: 'Uzbek', yes: 'Ha', no: 'Yoʻq' },
    { code: 'vi', native: 'Tiếng Việt', english: 'Vietnamese', yes: 'Có', no: 'Không' },
    { code: 'cy', native: 'Cymraeg', english: 'Welsh', yes: 'Ie', no: 'Na' },
    { code: 'yi', native: 'ייִדיש', english: 'Yiddish', dir: 'rtl', yes: 'יאָ', no: 'ניין' },
];
window.texcomLanguage = function (code) {
    code = String(code || 'en');
    return TEXCOM_LANGUAGES.find(l => l.code === code)
        || TEXCOM_LANGUAGES.find(l => l.code.toLowerCase() === code.toLowerCase())
        || TEXCOM_LANGUAGES.find(l => l.code === code.split('-')[0])
        || TEXCOM_LANGUAGES[0];
};
